name: 'jjp-init'

networks:
  jjp-init-network:
    name: jjp-init-network

services:
  mysql:
    image: mysql:8.1
    container_name: jjp-init-mysql
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - jjp-init-network

volumes:
  mysql-data:
    driver: local